config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" } 

  
  root to: 'groups#my'

  resources :groups, except: [:index, :destroy] do
    member do
      put :close
      get :buy
      post :checkout
      get :link
      patch :follow
      patch :delete_follow
    end
    collection do
      get :my
      get :attend
      get :public
      get :show_follow
    end
  end

  resources :orders, only: [:show]
  resources :thank, only: [:index]
  post "api/feedback" ,to: "api#feedback"

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'


end

app/models/group.rb
class Group < ApplicationRecord
  has_many :products, inverse_of: :group, :dependent => :destroy
  has_many :options, inverse_of: :group, :dependent => :destroy
  has_many :orders
  has_many :follows
  has_many :users, through: :follows
  accepts_nested_attributes_for :products, allow_destroy: true
  accepts_nested_attributes_for :options, allow_destroy: true
  belongs_to :user
  has_one_attached :shop_photo
  has_one_attached :qr_img
  validates :title, presence: true

  default_scope -> { order('created_at DESC') }

  def total_price
    orders.reduce(0){ |acc, order|
      acc + order.total_price
    }
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_group, only: [:edit, :update, :close, :link, :buy, :show, :checkout, :follow, :delete_follow]
  before_action :validate_group_owner, only: [:edit, :close, :update]
  before_action :validate_group_active, only: [:buy, :edit]

  def show
  end

  def my
    @groups = current_user.groups
  end

  def attend
    @groups = Order.where(buyer_id: current_user.id).map{ |order| order.group }.sort_by(&:created_at).reverse!.sort_by{ |group| group.is_active ? 0 : 1 }
  end

  def public
    @groups = Group.where(is_public: true)
  end

  def new
    if params[:group_id]
      @group = Group.find_by(id: params[:group_id])
      @group = current_user.groups.build(@group.as_json)
    else
      @group = current_user.groups.build
    end
  end

  def edit 
  end

  def update
    if @group.update(group_params)
      redirect_to my_groups_path
    else
      render :edit
    end
  end

  def create
    # 如果是用開過的團，要把 products 跟 options 裡面的 id 用掉
    group = group_params.permit(:title, :description, :address, :phone, :is_active, :start_time, :end_time, :is_public, :shop_photo, products_attributes:[:name, :price, :_destroy], options_attributes:[:name, :price, :_destroy])
    @group = current_user.groups.build(group)
    if @group.save
      redirect_to link_group_path(@group.id)
    else
      render :new
    end
  end

  def close
    @group.update(is_active: false, end_time: Time.now)
    redirect_to my_groups_path
  end


  def buy
    @products = @group.products
    @options = @group.options
  end

  def checkout
    order = Order.create(group: @group , buyer: current_user)

    params[:item].each do |i|
      product = Product.find_by(id: i["product"])
      
      order_item = OrderItem.create(order_id: order.id, product: product)
      
      i["options"].split(",").each do |option|
        OptionOrderItemLog.create(option_id: option.to_i, order_item_id: order_item.id)
      end
    end

    redirect_to order_path(order.id)
  end
  
  def link
    @link = buy_group_url
    respond_to do |format|
      format.html
      format.js
    end
  end


  def follow
    follow = current_user.follows.new(group_id: @group.id)
    if follow.save
      @ajax_result =  t('controllers.groups.follow.result')
      respond_to do |format|
        format.js
      end
    else
      @ajax_result = follow.errors.full_messages.join(', ')
    end
  end

  def show_follow
    @groups = current_user.followed_groups
  end

  def delete_follow
    current_user.followed_groups.delete(@group)
    @ajax_result =  t('controllers.groups.unfollow.result')
    respond_to do |format|
      format.js
    end
  end



  private
  def find_group
    @group = Group.find_by(id: params[:id])
  end

  def group_params
    clean_params = params.require(:group).permit(:title, :description, :address, :phone, :is_active, :start_time, :end_time, :is_public, :shop_photo, products_attributes:[:id, :name, :price, :_destroy], options_attributes:[:id, :name, :price, :_destroy])
  end

  def validate_group_owner
    if @group.user_id != current_user.id
      redirect_to my_groups_path, notice: "只有團主可以編輯/結單喔！"
    end
  end

  def validate_group_active
    unless @group.is_active 
      redirect_to my_groups_path, notice: "這個團已經結單囉！"
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_option_fields.html.erb
<div class="nested-fields row">
  <div class="col-5">
    <%= f.input :name, label: t("groups.option"), placeholder: t("groups.add_pearl") %>
  </div>
  <div class="col-5">
    <%= f.input :price, label: t("groups.price"), placeholder: "10" %>
  </div>
  <div class="col-2">
    <%= link_to_remove_association "X", f , class: "btn btn-delete"%>
  </div>
</div>

app/views/groups/_product_fields.html.erb
<div class="nested-fields row ">
  <div class="col-5">
    <%= f.input :name, label: t("groups.product_name"), placeholder: t("groups.milk_tea") %>
  </div>
  <div class="col-5">
    <%= f.input :price, label: t("groups.price"), placeholder: "50" %>
  </div>
  <div class="col-2">
    <%= link_to_remove_association "X", f , class: "btn btn-delete"%>
  </div>
</div>

app/views/groups/buy.html.erb
<script src="https://kit.fontawesome.com/2ddcd7dcfc.js" crossorigin="anonymous"></script>

<div class="wrap">
  <div class="box">  
    <div class="d-flex justify-content-start">
      <h1> <%= @group.title %> </h1>
      <div class="ml-2 mt-2">
        <%= link_to t("groups.follow_group_icon"), follow_group_path, class: "btn btn-warning btn-sm", method: 'patch', remote: true %>
      </div>
    </div>

    <div class = "container text-left mt-3 mb-4">
      <table class="table-sm  ta-info">
        <tr>
          <td class="ta-title"><i class="fa fa-phone"></i> <%= t("groups.phone") %></td>
          <td class="ta-content"> <%= @group.phone %> </td>
        </tr>
        <tr>
          <td class="ta-title"><i class="fa fa-map-marker"></i> <%= t("groups.address") %></td>
          <td class="ta-content"> <%= @group.address %> </td>
        </tr>
        
        <tr>
          <td class="ta-title"><i class="fas fa-comments"></i> <%= t("groups.description") %></td>
          <td class="ta-content"> <%= @group.description %> </td>
        </tr>
      
      </table>
  </div>









    <div class="menu-pic d-flex align-items-center justify-content-center mb-5">
      <% if @group.shop_photo.attached? %>
        <div class="row justify-content-center">
        <%= image_tag @group.shop_photo.variant(resize: "300x300"), class: "group-img " %>
        </div>
      <% end %>
    </div>


    <%# <div class="modal" tabindex="-1" role="dialog" id="myModal">
      <div class="modal-dialog" role="document">
        <div class="alert alert-info alert-dismissible fade show" role="alert">
          已加入購買清單!
        <button class="close" data-dismiss="alert">&times;</button></div>
      </div>
    </div> %>
    <div class="alert-con"></div>


  
  
    <div class="buy-pc">
      <div id="tab-demo" class="m-auto">
          <ul class="tab-title">
              <li><a href="#tab01"> <%= t("groups.join_group") %> </a></li>
              <li><a href="#tab02" id="checkout_paginate"><%= t("groups.check_order") %></a></li>
              <li><a href="#tab03"><%= t("groups.look_others") %></a></li>
          </ul>
    
          <div id="tab01" class="tab-inner">
            <form>
              <h6 class="border-bottom border-gray pb-2"><%= t("groups.select") %></h6>
              <div class="row media-body pb-3 lh-125 border-bottom border-gray mt-3">
                <div class="products col-6">
                  <% @products.each do |p| %>
                    <div class="product" data-product= "<%= p.id %>">
                      <%= radio_button_tag(:p, p.price ) %> <%= p.name %> <%= p.price %><%= t("groups.dollars") %>
                    </div>
                  <% end %>
                </div>
                <div class="options col-6">
                  <% @options.each do |o| %>
                    <div class="option" data-option= "<%= o.id %>">
                      <%= check_box_tag(:o, o.price) %>
                      <%= o.name %> <%= o.price %><%= t("groups.dollars") %>
                    </div>
                  <% end %>
                </div>
              </div>
              <div class="rounded mt-3"><%= t("groups.price") %>：<span class="total-price"></span></div>
              <button class='mt-3 btn btn-buy' id='buy'><%= t("groups.buy_buy") %></button>
            </form>
          </div>
    
          <div id="tab02" class="tab-inner">
            <h6 class="border-bottom border-gray pb-2"><%= t("groups.my_shop_list") %></h6>
            <div class="order-items text-muted">
              <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
              
              <%= form_with url: checkout_group_path, local: true do |form| %>
                <div id='order-item'>
                </div>
                <%= form.submit t("groups.checkout"), :class => 'mt-3 btn btn-pay' %>
              <% end %>
            </div>        
          </div>
    
          <div id="tab03" class="tab-inner">
              <h6><%= t("groups.all_shop_list") %></h6>
              <table class= "table">
                  <thead>
                  <tr>
                    <td><%= t("groups.buy_man") %></td>
                    <td><%= t("groups.product_name") %></td>
                    <td><%= t("groups.option") %></td>
                    <td><%= t("groups.product_price") %></td>
                    <td><%= t("groups.price") %></td>
                  </tr>
                  </thead>
                  <tbody>
                    <% @group.orders.each do |order| %>
                      <% order.order_items.each do |order_item| %>
                        <tr>
                          <td>
                            <%= order_item.order.buyer.name %>
                          </td>
                          <td>
                            <%= order_item.product.name %>
                          </td>
                          <td>
                            <% order_item.options.each do |option| %>
                              <%= option.name %>
                              (+<%= option.price %><%= t("groups.dollars") %>)
                            <% end %>
                          </td>
                          <td>
                            <%= order_item.product.price %>
                          </td>
                          <td>
                            <%= order_item.total_price %>
                          </td>
                        </tr>
                      <% end %>
                    <% end %>
                  </tbody>
              </table>
          </div>
          
      </div>
    </div>


    <div class="buy-phone">
      <div id="tab-demo" class="m-auto">
        <div div id="tab01" class="item others-list">
        <h2><%= t("groups.look_others") %></h2>
          <h6><%= t("groups.all_shop_list") %></h6>
          <table class= "table">
              <thead>
              <tr>
                <td><%= t("groups.buy_man") %></td>
                <td><%= t("groups.product_name") %></td>
                <td><%= t("groups.option") %></td>
                <td><%= t("groups.price") %></td>
              </tr>
              </thead>
              <tbody>
                <% @group.orders.each do |order| %>
                  <% order.order_items.each do |order_item| %>
                    <tr>
                      <td>
                        <%= order_item.order.buyer.name %>
                      </td>
                      <td>
                        <%= order_item.product.name %>
                      </td>
                      <td>
                        <% order_item.options.each do |option| %>
                          <%= option.name %>
                          (+<%= option.price %><%= t("groups.dollars") %>)
                        <% end %>
                      </td>
                      <td>
                        <%= order_item.total_price %>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
          </table>
        </div>

        <%# <hr class="mt-5"> %>

        
            <div id="tab02" class="item product-list">
              <h2><%= t("groups.join_group") %></h2>
              <form>
                <h6 class="border-bottom border-gray pb-2"><%= t("groups.select") %></h6>
                <div class="row media-body pb-3 lh-125 border-bottom border-gray mt-3">
                  <div class="products col-6">
                    <% @products.each do |p| %>
                      <div class="product" data-product= "<%= p.id %>">
                        <%= radio_button_tag(:p, p.price ) %> <%= p.name %> <%= p.price %><%= t("groups.dollars") %>
                      </div>
                    <% end %>
                  </div>
                  <div class="options col-6">
                    <% @options.each do |o| %>
                      <div class="option" data-option= "<%= o.id %>">
                        <%= check_box_tag(:o, o.price) %>
                        <%= o.name %> <%= o.price %><%= t("groups.dollars") %>
                      </div>
                    <% end %>
                  </div>
                </div>
                <div class="rounded mt-3"><%= t("groups.price") %>：<span class="total-price2"></span></div>
                <button class='mt-3 btn btn-buy' id='buy2'><%= t("groups.buy_buy") %></button>
              </form>
            </div>

            <%# <hr class="mt-5"> %>

            
            <div id="tab03" class="item option-list">
              <h2><%= t("groups.check_order") %></h2>
              <h6 class="border-bottom border-gray pb-2"><%= t("groups.my_shop_list") %></h6>
              <div class="order-items text-muted">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                
                <%= form_with url: checkout_group_path, local: true do |form| %>
                  <div id='order-item2'>
                  </div>
                  <%= form.submit t("groups.checkout"), :class => 'mt-3 btn btn-pay' %>
                <% end %>
              </div>        
            </div>
      </div>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<div class="wrap">
  <div class="box">
    <h1 class="mt-3 text-center text-dark">編輯團購</h1>
    <div class= "notice-space"><%= flash[:notice] %></div>
    <%= render 'form', group: @group, action: params[:action] %>
  </div>
</div>

app/views/groups/follow.js.erb
alert('<%= @ajax_result %>')
$('.fav[data-pid="<%=@group.id%>"] .star-nil').remove();
$('.fav[data-pid="<%=@group.id%>"]').prepend("<%= j(follow_btn(@group))%>")

app/views/groups/index.html.erb
4567

app/views/groups/link.js.erb
$('#event_area').html("<%= escape_javascript(render :partial => 'event') %>")
$('#qrcode-modal').modal('show');

app/views/groups/my.html.erb
  <div id="wrapper"  >
    <%= render 'shared/sidebar' %>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column mb-5">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->

        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container mt-5">
          <!-- Page Heading -->
          <h1 class="h3 text-heading"> <%= t("groups.my_group") %> </h1>

          <!-- DataTales Example -->
          <div class="mac card-group">
              <div class="row">
                <% if @groups.count == 0 %>
                  <div class="newuser_guide card text-center mx-auto p-3">
                    <div class="ml-1 row p-2 justify-content-center">
                    <p>
                    <%= t("groups.still_no_group") %>
                    </p>
                    <p>
                    <%= t("groups.can_click_public") %>
                    </p>
                      <div class="col-4">
                        <%= link_to t("groups.new_group"), new_group_path, class: "btn btn-reopen" %>
                      </div>
                    </div>
                  </div>
                <% end %>
                <% @groups.each do |group| %>
                <div class="card">
                  <div class="row p-2">
                    <div class="card-img-left col-4">
                      <% if group.shop_photo.attached? %>
                        <%= image_tag group.shop_photo, class: "default-pic" %>
                      <% else %>
                        <%= image_tag("logo.png", :alt => "logo", class:"default-pic") %>
                      <% end %>
                    </div>
                  
                  
                    <div class="col-8 text-dark">
                      <div class="pc-card-title">
                        <h2 class="card-title mt-2">
                          <% if group.is_active == true %>
                            <%= link_to group.title, link_group_path(group.id), class: "text-primary", :remote => true %>
                          <% else%>
                            <%= group.title %>
                          <% end %>
                        </h2>
                        <div class="fav" data-pid= "<%=group.id %>">
                          <%= follow_btn(group) %>
                        </div>
                      </div>
                      <p><i class="fas fa-comments"></i> <%= group.description %></p>
                      
                      <div class="d-flex justify-content-start">
                        
                        <div class="status mr-1">
                          <%= link_to t("groups.see_status"), group_path(group.id), class: "btn btn-sm btn-status" %>
                        </div>
                        <div class="status mr-1">
                          <% if group.is_active == true %>
                            <%= link_to t("groups.close_group"), close_group_path(group.id), class: "btn btn-sm btn-close", method: "put", data: {confirm: t("groups.confirm_close")} %>
                          <% else%>
                            <%= link_to t("groups.create_again"),new_group_path(:group_id => group.id), class: "btn btn-sm btn-reopen"%>
                          <% end %>
                        </div>
                        <div class="status mr-1">
                          <%= link_to t("groups.edit"), edit_group_path(group.id), class: "btn btn-sm btn-reopen" if group.is_active %>
                        </div>

                      </div>
                      <hr>
                      <div class="time mb-2 pc-time_block">
                        <i class="far fa-clock"></i> 
                        <span class="mr-3">
                          <%= group.created_at.to_s(:common) %> 
                          <% unless group.is_active %>
                          ~ <%= group.end_time.to_s(:common) if group.end_time %>
                          <% end %>
                        </span>
                      </div>
                    </div>
                  </div>
                   </div>
                <% end %>
             
            </div>
          </div>


          <div class="phone-card">
            <% if @groups.count == 0 %>
              <div class="newuser_guide card text-center mx-auto">
                <div class="row p-2 justify-content-center p-3">
                <p>
                <%= t("groups.still_no_group") %>
                </p>
                <p>
                <%= t("groups.can_click_public") %>
                </p>
                  <div class="mt-auto">
                    <%= link_to t("groups.new_group"), new_group_path, class: "btn btn-reopen" %>
                  </div>
                </div>
              </div>
            <% end %>
            <% @groups.each do |group| %>
              <div class="card mt-3">
                <div class="card-body text-dark">
                  <div class="card-img-top">
                    <% if group.shop_photo.attached? %>
                      <%= image_tag group.shop_photo, class: "default-pic" %>
                    <% else %>
                        <%= image_tag("logo.png", :alt => "logo", class:"default-pic") %>
                    <% end %>
                  </div>
                  <h3 class="card-title">
                    <% if group.is_active == true %>
                      <%= link_to group.title, link_group_path(group.id), class: "text-primary", :remote => true %>
                    <% else%>
                      <%= group.title %>
                    <% end %>
                  </h3>
                  <div class="fav" data-pid= "<%=group.id %>">
                    <%= follow_btn(group) %>
                  </div>


                  <h6 class="card-subtitle mb-2"><i class="fas fa-comments"></i>  <%= group.description %> </h6>
                  <% if group.is_active == true %>
                    <%= link_to t("groups.close_group"), close_group_path(group.id), class: "btn btn-close btn-sm", method: "put", data: {confirm: t("groups.confirm_close")} %>
                  <% else%>
                    <%= link_to t("groups.create_again"),new_group_path(:group_id => group.id), class: "btn btn-reopen btn-sm" %>
                  <% end %>
                  <%= link_to t("groups.see_status"), group_path(group.id), class: "btn btn-status btn-sm" %>
                  <div class="time mt-2">
                    <i class="far fa-clock"></i> 
                    <span class="mr-3">
                      <%= group.created_at.to_s(:common) %> 
                    </span>
                    <% unless group.is_active %>
                      <div>
                        ~ <%= group.end_time.to_s(:common) if group.end_time %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <div class="modal" tabindex="-1" role="dialog" id="qrcode-modal">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title"><%= t("groups.your_link") %></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div id="event_area"></div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-dark" data-dismiss="modal">關閉</button> 
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <%= render "footer" %>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->


  </div>

app/views/groups/new.html.erb
<div class="wrap">
  <div class="box">
    <h1 class="mt-3 text-center text-dark"> <%= t("groups.come_create") %> </h1>
    <%= render 'form', group: @group, action: params[:action] %>
  </div>
</div>

app/views/groups/show_follow.html.erb
  <div id="wrapper"  >
    <%= render 'shared/sidebar' %>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column mb-5">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->

        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container mt-5">
          <!-- Page Heading -->
          <h1 class="h3 text-heading"> <%= t("groups.follow_group") %> </h1>

          <!-- DataTales Example -->
          <div class="mac card-group">
            <div class="row">
              <% @groups.each do |group| %>
              <div class="card dele" data-cid= "<%=group.id %>">
                <div class="row p-2">
                  <div class="card-img-left col-4">
                    <% if group.shop_photo.attached? %>
                      <%= image_tag group.shop_photo, class: "default-pic" %>
                    <% else %>
                        <%= image_tag("logo.png", :alt => "logo", class:"default-pic") %>
                    <% end %>
                  </div>
                
                
                  <div class="col-8 text-dark">
                    <div class="pc-card-title">
                      <h2 class="card-title mt-2">
                        <% if group.is_active == true %>
                          <%= link_to group.title, link_group_path(group.id), class: "text-primary", :remote => true %>
                        <% else%>
                          <%= group.title %>
                        <% end %>
                      </h2>
                      <div class="fav" data-pid= "<%=group.id %>">
                        <%= follow_btn(group) %>
                      </div>
                    </div>
                    <div class="text-wrap-wrap d-flex justify-content-start">
                      <div class="text-wrap mr-1">
                        <% if group.is_active == true %>
                          <span class="badge badge-primary">
                            <%= t("groups.not_close") %>
                          </span>
                        <% else%>
                          <span class="badge badge-secondary">
                            <%= t("groups.closed") %>
                          </span>
                        <% end %>
                      </div>
                    </div>
                    <div class="text-content mb-3">
                      <p><i class="fas fa-comments"></i> <%= group.description %></p>
                      <p><i class="fas fa-user-friends"></i> <%= t("groups.group_owner") %>： <%= group.user.nick_name %></p>
                    </div>
                    
                    <div class="d-flex justify-content-start mb-3">
                      <div class="status mr-1">
                        <%= link_to t("groups.see_status"), group_path(group.id), class: "btn btn-status btn-sm" %>
                        <% if group.is_active == false %>
                          <%= link_to t("groups.create_again"),new_group_path(:group_id => group.id), class: "btn btn-reopen btn-sm" %>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>


          

          <div class="phone-card">
            <% @groups.each do |group| %>
              <div class="card mt-3 dele" data-cid= "<%=group.id %>">
                <div class="card-body">
                 <div class="card-img-top">
                    <% if group.shop_photo.attached? %>
                      <%= image_tag group.shop_photo, class: "default-pic" %>
                    <% else %>
                        <%= image_tag("logo.png", :alt => "logo", class:"default-pic") %>
                    <% end %>
                  </div>
                  <h3 class="card-title">
                    <% if group.is_active == true %>
                      <%= link_to group.title, link_group_path(group.id), class: "text-primary", :remote => true %>
                    <% else%>
                      <%= group.title %>
                    <% end %>
                  </h3>
                  <div class="fav" data-pid= "<%=group.id %>">
                    <%= follow_btn(group) %>
                  </div>
                  <div class="text-wrap-wrap d-flex justify-content-center">
                    <div class="text-wrap mr-2">
                      <% if group.is_active == true %>
                        <span class="badge badge-primary">
                          <%= t("groups.not_close") %>
                        </span>
                      <% else%>
                        <span class="badge badge-secondary">
                          <%= t("groups.closed") %>
                        </span>
                      <% end %>
                    </div>
                  </div>
                  <div class="text-content text-dark mb-2">
                      <p><i class="fas fa-comments"></i> <%= group.description %></p>
                      <p><i class="fas fa-user-friends"></i> <%= t("groups.group_owner") %>： <%= group.user.nick_name %></p>
                  </div>
                  <% unless group.is_active == true %>
                    <%= link_to t("groups.create_again"),new_group_path(:group_id => group.id), class: "btn btn-reopen btn-sm" %>
                  <% end %>
                  <%= link_to t("groups.see_status"), group_path(group.id), class: "btn btn-status btn-sm" %>
                  <div class="time mt-2 pc-time_block">
                    <i class="far fa-clock"></i>   
                    <span class="mr-3">
                      <%= group.created_at.to_s(:common) %> 
                    </span>
                    <% unless group.is_active %>
                      <div>
                        ~ <%= group.end_time.to_s(:common) if group.end_time %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <div class="modal" tabindex="-1" role="dialog" id="qrcode-modal">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title"><%= t("groups.your_link") %></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div id="event_area"></div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-dark" data-dismiss="modal">關閉</button> 
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <%= render "footer" %>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->


  </div>